WIP: First draft of did-pkh method.
uport-project/veramo pull request #1052
Opened 2022-11-02 20:07 UTC by dchagastelles

- Create new pkh-did-provider
The pkh-did-provider supports only eip155 network id (did:pkh:eip155:...) so for now the network id is hardcoded, but we could easily parameterize to support other networks.

- Add resolve did-pkh tests
Tests passing 

- Add create did-pkh identifier test
Tests passing

- Add VC creation/verification using did-pkh identifier
Test not passing **"should create verifiable credential in LD with did:pkh"** 
Need help here, the error I have:
`key_not_found: No suitable signing key found for did:pkh:eip155:mainnet:0x037ecebcd07546915775077ec90fdcf89f907e97fcc459116ad165780eafc8aaca `

By debugging and comparing with did:key equivalent test, it appears the did:pkh resolved DidDocument don't have a property publicKeyHex or publicKeyBase58 on its VerificationMethod object, which causes it to not find the signing key. 

did-key resolved DIDDocument has it:
![image](https://user-images.githubusercontent.com/4438399/199591579-c99f0c20-be7a-48e5-9c7f-057c37407ab0.png)

did-pkh resolved DIDDocument don't:
![image](https://user-images.githubusercontent.com/4438399/199592009-6905e0a7-4381-45c2-a32e-6be170239c23.png)

as per the did-pkh specification https://github.com/w3c-ccg/did-pkh/blob/main/did-pkh-method-draft.md

![image](https://user-images.githubusercontent.com/4438399/199592270-c4e3329c-0208-4d47-8792-f32e556e2bdd.png)

## Detail
Currently not using pkh-did-resolver package (error import). Code momentarily copied to did-provider-pkh resolver.

## What issue is this PR fixing
Resolves #1024 (not yet)

## Quality
Check all that apply:
* [X] I want these changes to be integrated
* [ ] I successfully ran `yarn`, `yarn build`, `yarn test`, `yarn test:browser` locally.
* [X] I allow my PR to be updated by the reviewers (to speed up the review process).
* [ ] I added unit tests.
* [X] I added integration tests.

2022-11-17 13:02 UTC, mirceanis requested changes
Thank you for contributing this and apologies for taking so long to review.

I made some suggestions to fix the failing test.
The DID string for eip155 is formed using the ethereum address, not the compressed public key. This was also the cause of the test failures you were seeing.

Also, CAIP10/eip155 require chainIDs to be used in the `blockchainAccountId`, not network names.
`eip155:1:0xaddress` instead of `eip155:mainnet:0xaddress`

2022-11-17 13:28 UTC, mirceanis requested changes
I added another couple of suggested fixes to the tests.
Please take a look.

2022-11-17 13:28 UTC, mirceanis commented on __tests__/shared/verifiableDataLD.ts
> +        'https://veramo.io/contexts/profile/v1',
```suggestion
        'https://veramo.io/contexts/profile/v1',
        'https://w3id.org/security/suites/secp256k1recovery-2020/v2',
```

2022-11-17 13:28 UTC, mirceanis commented on __tests__/shared/verifiableDataLD.ts
> +        hash: storedCredentialHash,
```suggestion
        hash: storedPkhCredentialHash,
```

2022-11-21 18:58 UTC, dchagastelles commented on packages/did-provider-pkh/CHANGELOG.md
> +# Change Log
done.

2022-11-21 20:14 UTC, dchagastelles commented on packages/did-provider-pkh/src/pkh-did-provider.ts
> +      did: 'did:pkh:eip155:' + network + ':' + compressedPublicKey,
Used toEthereumAddress helper to obtain EthereumAddress directly from publickey hex.

2022-11-21 20:32 UTC, dchagastelles commented on packages/did-provider-ion/dist/tsdoc-metadata.json
> +// This file is read by tools that parse documentation comments conforming to the TSDoc standard.
removed

2022-11-23 15:13 UTC, nickreynolds commented
now that tests are passing, it would probably be a good time to rebase this branch against `next` to get rid of the extraneous commits

2022-11-28 17:47 UTC, mirceanis commented on packages/did-provider-pkh/package.json
> +    "typescript": "4.7.3"
align with existing versions
```suggestion
    "typescript": "4.8.4"
```

2022-11-28 17:56 UTC, mirceanis approved these changes
Looks good.
Thanks for contributing this!

2022-11-29 10:00 UTC, mirceanis commented on package.json
> +    "caip": "^1.1.0"
```suggestion
    "caip": "^1.1.0",
```

2022-11-30 07:52 UTC, mirceanis approved these changes

2022-11-30 18:27 UTC, merged