feat(did-comm): add trust ping protocol
uport-project/veramo pull request #1080
Opened 2022-11-30 03:24 UTC by nickreynolds

## What issue is this PR fixing
closes #1079 

## What is being changed
A clear description of what this PR brings.

## Quality
Check all that apply:
* [X] I want these changes to be integrated
* [ ] I successfully ran `yarn`, `yarn build`, `yarn test`, `yarn test:browser` locally.
* [ ] I allow my PR to be updated by the reviewers (to speed up the review process).
* [ ] I added unit tests.
* [ ] I added integration tests.
* [ ] I did not add automated tests because _________, and I am aware that a PR without tests will likely get rejected.

## Details
If applicable, add screen captures, error messages or stack traces to help explain your problem.

2022-11-30 03:25 UTC, nickreynolds commented on packages/did-comm/src/__tests__/trust-ping-message-handler.test.ts
> +    expect(DIDCommEventSniffer.onEvent).toHaveBeenCalledTimes(10)
this is currently failing, as recipient does not properly unpack message

2022-11-30 03:25 UTC, nickreynolds commented on packages/did-comm/src/__tests__/trust-ping-message-handler.test.ts
> +    expect(DIDCommEventSniffer.onEvent).toHaveBeenCalledTimes(2)
need a better check for these tests

2022-12-05 21:45 UTC, mirceanis requested changes
Looks good, kudos for the thorough testing!

It's a straight forward approach, using the message handler chain for this, and consistent with the existing codebase.
I'm not sure if this is a problem for this protocol, but this can be triggered by any message that looks like a trust ping, even if it doesn't come through didcomm. 

Another possible approach for protocol implementations would be to create protocol handlers as agent plugins that react based on event listeners.
Maybe for future protocols we can also explore this option but we need to figure out how to forward events for agents that use `@veramo/remote-client`

That being said, now with a new message handler supported, we should also update our default CLI config file.

2022-12-05 21:45 UTC, mirceanis commented on packages/message-handler/src/abstract-message-handler.ts
> +    console.warn("Can't handle message: ", message)
We should be using the `debug` module for this kind of logging, since that can be switched off or filtered.

2022-12-05 21:45 UTC, mirceanis commented on packages/did-comm/src/protocols/trust-ping-message-handler.ts
> +          throw new Error("Trust Ping Message received without `from` set")
Let's use a prefix for errors, for consistency.

In this case, something like `invalid_argument: Trust Ping Message received without "from" set`

2022-12-05 21:45 UTC, mirceanis commented on packages/did-comm/src/__tests__/message-handler.test.ts
> +  it('should pack and unpack trust ping message with none packing', async () => {
I think the test name should refer to regular message here instead, no?

2022-12-05 21:45 UTC, mirceanis commented on __tests__/shared/didCommPacking.ts
> +      console.log("packedMessage: ", packedMessage)
If these logs were used for debug, they should be removed to reduce the noise in tests

2022-12-05 22:07 UTC, nickreynolds commented
> It's a straight forward approach, using the message handler chain for this, and consistent with the existing codebase. I'm not sure if this is a problem for this protocol, but this can be triggered by any message that looks like a trust ping, even if it doesn't come through didcomm.
> 
> Another possible approach for protocol implementations would be to create protocol handlers as agent plugins that react based on event listeners.

@mirceanis 

Yeah, it being able to be triggered by "non didcomm messages" was intentional. It at least makes testing a bit easier since it can be separated from didcomm's own message handler. I don't feel strongly though, but it seems fine to do it this way?

I was considering using the event listener system as well, but it seemed to work well with the message handler flow. If we decide that other "didcomm protocols" should use the event system, I can refactor this one at that time.

Made the small changes you requested

2022-12-05 22:23 UTC, mirceanis approved these changes
Looks great!

Yeah, we can refactor to event system later, if needed.

Please also consider adding this new handler to the default CLI config

2022-12-06 02:13 UTC, merged