Improvements on did-provider-pkh plugin
uport-project/veramo pull request #1113
Opened 2023-02-02 14:46 UTC by dchagastelles

## What issue is this PR fixing
There's no issue being fixed, just small improvements on did-provider-pkh plugin:

- minor parameters corrections
- use of namespace parameter
- allow passing privateKey to import key directly on identifier creation

## What is being changed
Only changing did-provider-pkh plugin. 

## Quality
Check all that apply:
* [X] I want these changes to be integrated
* [X] I successfully ran `pnpm i`, `pnpm build`, `pnpm test`, `pnpm test:browser` locally.
* [X] I allow my PR to be updated by the reviewers (to speed up the review process).
* [ ] I added unit tests. 
* [X] I added integration tests. [were already there]
* [ ] I did not add automated tests because _________, and I am aware that a PR without tests will likely get rejected.

2023-02-03 11:57 UTC, mirceanis requested changes
Thanks for contributing this.

Since this is meant to clean up some code, I also made some notes that should make this align better with the patterns we use in other parts of the codebase.
It's mostly about error messages and debug output. Please take a look.

2023-02-03 11:57 UTC, mirceanis commented on packages/did-provider-pkh/src/pkh-did-provider.ts
> +  chainId?: string;
Why not leave this as a number as well?
```suggestion
  chainId?: string | number;
```

2023-02-03 11:57 UTC, mirceanis commented on packages/did-provider-pkh/src/resolver.ts
> +      `Invalid namespace '${namespace}'. Valid namespaces are: ${SECPK1_NAMESPACES}`
```suggestion
      `illegal_argument: namespace '${namespace}' not supported. Valid namespaces are: ${SECPK1_NAMESPACES}`
```

2023-02-03 11:57 UTC, mirceanis commented on packages/did-provider-pkh/src/pkh-did-provider.ts
>   * Options for creating a did:ethr
```suggestion
 * Options for creating a did:pkh
```

2023-02-03 14:04 UTC, dchagastelles commented on packages/did-provider-pkh/src/pkh-did-provider.ts
> +      console.error(
done

2023-02-07 18:26 UTC, mirceanis requested changes
Thanks for the updates.
I suggested some more tiny fixes.

2023-02-07 18:26 UTC, mirceanis commented on packages/did-provider-pkh/src/pkh-did-provider.ts
> +const debug = Debug('veramo:data-store:migrate-presentation-issuance-date')
```suggestion
const debug = Debug('veramo:pkh-did-provider')
```

2023-02-07 18:26 UTC, mirceanis commented on packages/did-provider-pkh/src/pkh-did-provider.ts
> +      throw new Error('Could not create identifier due to some errors');
```suggestion
      throw new Error('unknown_error: could not create identifier due to errors creating or importing keys');
```

2023-02-07 18:26 UTC, mirceanis commented on packages/did-provider-pkh/src/resolver.ts
```suggestion
import Debug from 'debug'

const debug = Debug('veramo:pkh-did-resolver')
```

2023-02-07 18:26 UTC, mirceanis commented on packages/did-provider-pkh/src/resolver.ts
> +    console.error(
```suggestion
    debug(
```

2023-02-07 19:27 UTC, mirceanis approved these changes

2023-02-07 19:27 UTC, merged