Add Key value store based on a typescript port of the keyv package
uport-project/veramo pull request #1150
Opened 2023-03-22 13:58 UTC by nklomp

This is a Key Value store with a typescript port of the Keyv package (https://github.com/jaredwray/keyv)., ESM compatible and should work in browser/Node/React-Native (not tested yet)

Includes TypeORM, Map based and Tiered Key Value storage adapters.

Lastly there is a separate API/Interfaces within Veramo, to not expose core data types from the package.

Obviously still needs more work (for instance I want to seperate the RAW and non RAW getters, because I really dislike the polymorph responses from the original package.

Of course also needs way more testing. Just looking at some initial feedback

2023-04-11 09:27 UTC, simonas-notcat requested changes
Since this plugin is introducing top level methods, it has to have a `plugin.schema.json` file which is going to be used when generating OpenAPI schema for remote method execution. This means that the interface and arguments of these methods have to be serialisable.

You have to add this section to the `package.json` file:
```json
  "veramo": {
    "pluginInterfaces": {
      "IKeyValueStore": "./src/key-value-types.ts"
    }
  },
```

and add this line to the `scripts` section:
```json
"generate-plugin-schema": "node ../cli/bin/veramo.js dev generate-plugin-schema"
```

When you do this, you will see that this script is complaining about the types. I think the issue is that you are using `<ValueType>` in interface definitions. I don't think this is supported by the tools we are using for schema generation.

2023-05-03 00:23 UTC, nklomp commented
Hi @simonas-notcat Thanks for the review and sorry for not getting back sooner. It has been a bit hectic over here.

I am not sure about your plugin/schema comment. This is not a Veramo plugin to be clear. It is more like the key manager, or even better the data-store. Both which are not exposing a plugin schema.

It is not a plugin, because you might want to use one or more KV stores in your own plugins. Then you want to have typed values for your keys per KV store. You are not going to call a KV Veramo instance remotely, you would use a remote backing store, like a TypeORM DB or Mongo for instance.

2023-05-05 13:41 UTC, simonas-notcat commented
> This is not a Veramo plugin to be clear.

Sorry I did not realise that. Now it makes sense. Looks good to me

2023-05-05 13:42 UTC, simonas-notcat approved these changes

2023-05-10 20:10 UTC, nklomp commented
@mirceanis Do you also want to do a review or chime in on the PR, given you had some opinions/suggestions in Discord as well?

2023-05-18 18:02 UTC, mirceanis reviewed
Looks great! There are just a few nits.

2023-05-18 18:27 UTC, nklomp commented on packages/kv-store/src/key-value-store.ts
> +    }
If I am not mistaken the original package always has the property. But indeed we don't necessarily have to do that, as we are using our own types anyway,

2023-05-18 18:27 UTC, nklomp commented on packages/kv-store/src/key-value-store.ts
> + * @public
Leftover from when I started I guess. Will remove it

2023-05-18 19:01 UTC, nklomp commented on packages/kv-store/src/key-value-store.ts
> + * @public
Removed in latest commit

2023-05-18 19:10 UTC, nklomp commented on packages/cli/src/dev.ts
> +  let fixedSymbol = symbol.replace(/Array\<(.*)\>/gm, '$1')
@mirceanis Just wanted to highlight this change outside of the kv-store package. When testing a bit with the schema-generator I noticed that it mangled anything with carets in there, whilst it was only intended for Arrays.

2023-05-18 19:11 UTC, nklomp commented
Okay comments are addressed.

2 things:
- I took the liberty to add myself to the list of Authors
- See the remark about the change in the CLI package

2023-05-19 11:58 UTC, mirceanis commented
> * I took the liberty to add myself to the list of Authors

That's exactly how it should be :)
We value your contributions greatly!

2023-05-19 12:00 UTC, merged