added did:key provider; fixes #335
uport-project/veramo pull request #351
Opened 2021-01-26 13:23 UTC by awoie

added did:key provider; fixes #335

2021-01-26 13:40 UTC, mirceanis requested changes
Nice work!

I flagged some tiny changes that need to be done and it would also be nice to see some tests with this, like checking that a credential issued by a `did:key` looks ok, or that calling the CRUD methods to modify the DID document throw expected errors.

2021-01-26 13:40 UTC, mirceanis commented on packages/did-provider-key/CHANGELOG.md
> +# Change Log
This file should be removed

2021-01-26 13:40 UTC, mirceanis commented on packages/did-provider-key/src/index.ts
> + * Provides `did:web` {@link @veramo/did-provider-key#KeyDIDProvider | identifier provider } for the
This should reference did:key, not did:web
```suggestion
 * Provides `did:key` {@link @veramo/did-provider-key#KeyDIDProvider | identifier provider } for the
```

2021-01-26 16:31 UTC, jasonhealy commented
@awoie If you want the provider to be documented you  need to add it in here: https://github.com/uport-project/veramo/blob/awoie/did-key/docsconfig.json

example doc: http://veramo.io/docs/api/did-provider-ethr.ethrdidprovider

2021-01-28 13:20 UTC, mirceanis approved these changes
looks good

2021-01-28 14:13 UTC, merged