Add choices when selecting credential Subject in CLI
uport-project/veramo pull request #898
Opened 2022-05-26 02:58 UTC by tientaidev

Adding choices when select Subject DID instead of always default it to the first identifier. 
This PR fix issues mentioned in #897

2022-05-26 10:29 UTC, simonas-notcat requested changes
@tientaidev , thanks for your contribution! I would suggest using `type: 'autocomplete'`, so that it's possible to select a DID from a list of known DIDs, but also to manually input any DID. Take a look at how it is done in `sdr` flow:

https://github.com/uport-project/veramo/blob/next/packages/cli/src/sdr.ts#L39

2022-05-26 14:29 UTC, mirceanis requested changes
Thank you for the contribution!

The validation is a bit too strict, but otherwise it looks good.

2022-05-26 14:29 UTC, mirceanis commented on packages/cli/src/credential.ts
> +          if (!val || !val.startsWith('did:')) {
A subject can be a plain URL, it doesn't have to start with `did:`

It is even OK if the subject is missing, in which case the `credentialSubject.id` property of the credential should be omitted.

2022-05-26 14:31 UTC, mirceanis commented on packages/cli/src/credential.ts
> +          if (!val || !val.startsWith('did:')) {
if using anything other than a DID causes issues in other places, we can merge this as is and fix the other places later, but please flag it if that is the case

2022-05-27 19:26 UTC, mirceanis approved these changes
Looks great,
Thank you!

2022-05-27 19:26 UTC, merged